m = 0.5; sigma = 0.5; alpha=0.05;
x = normrnd(m, sigma, 100, 1);
[muhat, sigmahat, muci, sigmaci] = normfit(x,alpha);
q = fminsearch('customnormfit', [m, sigma], [], x);
fprintf('Нормальное распределение:\n');
fprintf('m  = %.3f\ns  = %.3f\n', m, sigma);
fprintf('Максимально правдоподобные точечные оценки:\n');    
fprintf('Средства Matlab:\n'); 
fprintf('m^ = %.3f\ns^ = %.3f\n', muhat, sigmahat);
fprintf('Собственный алгоритм:\n'); 
fprintf('m^ = %.3f\ns^ = %.3f\n', q(1), q(2));
n = 10; p = 0.5;
x = binornd(n,p);
[phat, pci] = binofit(x,n,alpha);
q = fminsearch('custombinofit', [n, p], [], x);
fprintf('Биномиальное распределение:\n');
fprintf('n  = %.3f\np  = %.3f\n', n, p);
fprintf('Максимально правдоподобные точечные оценки:\n');
fprintf('Средства Matlab:\n'); 
fprintf('p^ = %.3f\n', phat(1));
fprintf('Собственный алгоритм:\n'); 
fprintf('n^ = %.3f\np^ = %.3f\n', q(1), q(2));
